
# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

defaults:
  - _self_
  - database: default
  - entities: default
  - override hydra/help: excel_summarize_help

input: ??? # path to input files
output: ??? # output filename

threshold: 0.5 # only summarize relations with confidence above threshold
no_association_type: false # ignore relation type (head and tail only)
top_k_articles: 5 # number of k article per pair (relation)
entity_set: null # Subset of entities whose relations with all other entities will be summarized
mesh_terms: null # Filter PubMed IDs using the specified MeSH terms
plain: false # Output plain csv instead of Excel file
