model_name: "leonweber/PEDL"
expand_species:
multi_sentence: False
num_workers: 1
worker_id: 0
local_model: False
max_sequence_length: 512
use_cls: False
use_starts: True
use_ends: False
num_labels: 7
head_type: Gene
tail_type: Gene
entity_to_mask:
  Gene: 'gene'

label_to_id :
  in-complex-with: 0
  controls-state-change-of: 1
  controls-transport-of: 2
  controls-phosphorylation-of: 3
  controls-expression-of: 4
  catalysis-precedes: 5
  interacts-with: 6
